# Organizing Dataframe

Here the data frame dowloaded will be cut down to necessary columns and
also user will be exctracted from the json files that has been created by the API dowloader file

In [1]:
import nltk
import pandas as pd

In [2]:
all_df = pd.read_csv('df_total_seperated.csv')

In [3]:
df1 = all_df.copy()

In [4]:
df1.head()

,_type,url,date,content,renderedContent,id,user,replyCount,retweetCount,likeCount,...,media,retweetedTweet,quotedTweet,inReplyToTweetId,inReplyToUser,mentionedUsers,coordinates,place,hashtags,cashtags
0,snscrape.modules.twitter.Tweet,https://twitter.com/aquitainexox/status/145641...,2021-11-04 23:59:50+00:00,@Banterm42404691 @MrHarryCole Absolutely one s...,@Banterm42404691 @MrHarryCole Absolutely one s...,1456410892422295556,"{'_type': 'snscrape.modules.twitter.User', 'us...",0,0,0,...,NaN,NaN,NaN,1.456408e+18,"{'_type': 'snscrape.modules.twitter.User', 'us...","[{'_type': 'snscrape.modules.twitter.User', 'u...",NaN,NaN,['COP26'],NaN
1,snscrape.modules.twitter.Tweet,https://twitter.com/GEC_JCM_Info/status/145641...,2021-11-04 23:59:48+00:00,"Please join us at a #COP26 side event ""Impleme...","Please join us at a #COP26 side event ""Impleme...",1456410883471523840,"{'_type': 'snscrape.modules.twitter.User', 'us...",0,1,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,['COP26'],NaN
2,snscrape.modules.twitter.Tweet,https://twitter.com/zpnine/status/145641087629...,2021-11-04 23:59:46+00:00,#India’s huge solar uptake has boosted #climat...,#India’s huge solar uptake has boosted #climat...,1456410876299329538,"{'_type': 'snscrape.modules.twitter.User', 'us...",0,0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"['India', 'climate', 'COP26']",NaN
3,snscrape.modules.twitter.Tweet,https://twitter.com/AsoPalabrasCl/status/14564...,2021-11-04 23:59:39+00:00,Reunión #COP26 Reunión mundial de países sobre...,Reunión #COP26 Reunión mundial de países sobre...,1456410848667348992,"{'_type': 'snscrape.modules.twitter.User', 'us...",0,0,0,...,NaN,NaN,"{'_type': 'snscrape.modules.twitter.Tweet', 'u...",NaN,NaN,NaN,NaN,NaN,"['COP26', 'AcuerdoDeParis', 'LenguajeClaro']",NaN
4,snscrape.modules.twitter.Tweet,https://twitter.com/Crstianst/status/145641082...,2021-11-04 23:59:35+00:00,@_pln_id PLN terdepan dukung pemanfaatan EBT🍃\...,@_pln_id PLN terdepan dukung pemanfaatan EBT🍃\...,1456410828974952480,"{'_type': 'snscrape.modules.twitter.User', 'us...",0,0,0,...,NaN,NaN,NaN,1.455825e+18,"{'_type': 'snscrape.modules.twitter.User', 'us...","[{'_type': 'snscrape.modules.twitter.User', 'u...",NaN,NaN,"['COP26', 'PLNGreen']",NaN

In [5]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 28 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   _type             10000 non-null  object
 1   url               10000 non-null  object
 2   date              10000 non-null  object
 3   content           10000 non-null  object
 4   renderedContent   10000 non-null  object
 5   id                10000 non-null  int64
 6   user              10000 non-null  object
 7   replyCount        10000 non-null  int64
 8   retweetCount      10000 non-null  int64
 9   likeCount         10000 non-null  int64
 10  quoteCount        10000 non-null  int64
 11  conversationId    10000 non-null  int64
 12  lang              10000 non-null  object
 13  source            10000 non-null  object
 14  sourceUrl         10000 non-null  object
 15  sourceLabel       10000 non-null  object
 16  outlinks          5660 non-null   object
 17  tcooutlinks       5660 non-null   object
 18  media             3336 non-null   object
 19  retweetedTweet    0 non-null      float64
 20  quotedTweet       2190 non-null   object
 21  inReplyToTweetId  1324 non-null   float64
 22  inReplyToUser     1324 non-null   object
 23  mentionedUsers    4476 non-null   object
 24  coordinates       329 non-null    object
 25  place             329 non-null    object
 26  hashtags          10000 non-null  object
 27  cashtags          24 non-null     object
dtypes: float64(2), int64(6), object(20)
memory usage: 2.1+ MB

In [6]:
df1[df1['content'].duplicated()]

,_type,url,date,content,renderedContent,id,user,replyCount,retweetCount,likeCount,...,media,retweetedTweet,quotedTweet,inReplyToTweetId,inReplyToUser,mentionedUsers,coordinates,place,hashtags,cashtags
520,snscrape.modules.twitter.Tweet,https://twitter.com/DindaSylwa/status/14564027...,2021-11-04 23:27:36+00:00,@_pln_id #PLN #PLNGreen #COP26 #COP26Glasgow #...,@_pln_id #PLN #PLNGreen #COP26 #COP26Glasgow #...,1456402782756294657,"{'_type': 'snscrape.modules.twitter.User', 'us...",0,0,0,...,NaN,NaN,NaN,1.455825e+18,"{'_type': 'snscrape.modules.twitter.User', 'us...","[{'_type': 'snscrape.modules.twitter.User', 'u...",NaN,NaN,"['PLN', 'PLNGreen', 'COP26', 'COP26Glasgow', '...",NaN
646,snscrape.modules.twitter.Tweet,https://twitter.com/Rachel__Sarah/status/14564...,2021-11-04 23:20:32+00:00,Thank you for your time and voices to write th...,Thank you for your time and voices to write th...,1456401002651795465,"{'_type': 'snscrape.modules.twitter.User', 'us...",0,0,3,...,NaN,NaN,"{'_type': 'snscrape.modules.twitter.Tweet', 'u...",NaN,NaN,"[{'_type': 'snscrape.modules.twitter.User', 'u...",NaN,NaN,"['COP26', 'MissingVoicesCOP26']",NaN
685,snscrape.modules.twitter.Tweet,https://twitter.com/realjosev/status/145640053...,2021-11-04 23:18:40+00:00,#COP26,#COP26,1456400535297400838,"{'_type': 'snscrape.modules.twitter.User', 'us...",0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,['COP26'],NaN
1613,snscrape.modules.twitter.Tweet,https://twitter.com/nickwer888/status/14563885...,2021-11-04 22:30:51+00:00,👋 @juancabandie @joaquimleitemma @sitinurbayal...,👋 @juancabandie @joaquimleitemma @sitinurbayal...,1456388501503713290,"{'_type': 'snscrape.modules.twitter.User', 'us...",0,0,0,...,NaN,NaN,NaN,NaN,NaN,"[{'_type': 'snscrape.modules.twitter.User', 'u...",NaN,NaN,"['G20', 'COP26']",NaN
1777,snscrape.modules.twitter.Tweet,https://twitter.com/disclosetv/status/14563867...,2021-11-04 22:23:48+00:00,JUST IN - White House aide traveling with Bide...,JUST IN - White House aide traveling with Bide...,1456386726683873280,"{'_type': 'snscrape.modules.twitter.User', 'us...",731,2408,8372,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"['COP26', 'COVID19']",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,snscrape.modules.twitter.Tweet,https://twitter.com/LauraEAlex1/status/1455595...,2021-11-02 18:00:27+00:00,#ScotlandIsCalling #islands #ferries #LoveNort...,#ScotlandIsCalling #islands #ferries #LoveNort...,1455595675434037250,"{'_type': 'snscrape.modules.twitter.User', 'us...",0,1,2,...,"[{'_type': 'snscrape.modules.twitter.Photo', '...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,"['ScotlandIsCalling', 'islands', 'ferries', 'L...",NaN
9996,snscrape.modules.twitter.Tweet,https://twitter.com/SUMEETGOSWAMI/status/14555...,2021-11-02 18:00:15+00:00,PM #Modi Ji Unbeatable #G20 #GlasgowCop26 http...,PM #Modi Ji Unbeatable #G20 #GlasgowCop26 http...,1455595627539165192,"{'_type': 'snscrape.modules.twitter.User', 'us...",0,0,0,...,"[{'_type': 'snscrape.modules.twitter.Photo', '...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,"['Modi', 'G20', 'GlasgowCop26']",NaN
9997,snscrape.modules.twitter.Tweet,https://twitter.com/Jans_Arbor/status/14555956...,2021-11-02 18:00:13+00:00,#LópezTerroristaClimático #COP26 #GlasgowCop26...,#LópezTerroristaClimático #COP26 #GlasgowCop26...,1455595617900802054,"{'_type': 'snscrape.modules.twitter.User', 'us...",0,0,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"['LópezTerroristaClimático', 'COP26', 'Glasgow...",NaN
9998,snscrape.modules.twitter.Tweet,https://twitter.com/OttoemezzoTW/status/145559...,2021-11-02 18:00:01+00:00,#ottoemezzo Da #GlasgowCop26 a Roma: il #BlaBl...,#ottoemezzo Da #GlasgowCop26 a Roma: il #BlaBl...,1455595567233462282,"{'_type': 'snscrape.modules.twitter.User', 'us...",55,10,57,...,"[{'_type': 'snscrape.modules.twitter.Photo', '...",NaN,NaN,NaN,NaN,"[{'_type': 'snscrape.modules.twitter.User', 'u...",NaN,NaN,"['ottoemezzo', 'GlasgowCop26', 'BlaBlaBla', 'D...",NaN
9999,snscrape.modules.twitter.Tweet,https://twitter.com/jecastelan/status/14555955...,2021-11-02 17:59:59+00:00,Buen día @lopezobrador_ @Mary_Luisa_AG @m_ebra...,Buen día @lopezobrador_ @Mary_Luisa_AG @m_ebra...,1455595559146954754,"{'_type': 'snscrape.modules.twitter.User', 'us...",0,0,0,...,NaN,NaN,"{'_type': 'snscrape.modules.twitter.Tweet', 'u...",NaN,NaN,"[{'_type': 'snscrape.modules.twitter.User', 'u...",NaN,NaN,"['Mexico', 'GlasgowCop26', 'COP26', 'CambioCli...",NaN

In [7]:
#dropping dublicates in regards of contents wheich are the tweets repeated.
#since we got 5 hashtags and might have pulled same tweets.
df1.drop_duplicates(subset=['content'],keep='first',inplace=True)

### Dataftame with no dupilcates

In [8]:
#dataftame with no dupilcates
df1

,_type,url,date,content,renderedContent,id,user,replyCount,retweetCount,likeCount,...,media,retweetedTweet,quotedTweet,inReplyToTweetId,inReplyToUser,mentionedUsers,coordinates,place,hashtags,cashtags
0,snscrape.modules.twitter.Tweet,https://twitter.com/aquitainexox/status/145641...,2021-11-04 23:59:50+00:00,@Banterm42404691 @MrHarryCole Absolutely one s...,@Banterm42404691 @MrHarryCole Absolutely one s...,1456410892422295556,"{'_type': 'snscrape.modules.twitter.User', 'us...",0,0,0,...,NaN,NaN,NaN,1.456408e+18,"{'_type': 'snscrape.modules.twitter.User', 'us...","[{'_type': 'snscrape.modules.twitter.User', 'u...",NaN,NaN,['COP26'],NaN
1,snscrape.modules.twitter.Tweet,https://twitter.com/GEC_JCM_Info/status/145641...,2021-11-04 23:59:48+00:00,"Please join us at a #COP26 side event ""Impleme...","Please join us at a #COP26 side event ""Impleme...",1456410883471523840,"{'_type': 'snscrape.modules.twitter.User', 'us...",0,1,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,['COP26'],NaN
2,snscrape.modules.twitter.Tweet,https://twitter.com/zpnine/status/145641087629...,2021-11-04 23:59:46+00:00,#India’s huge solar uptake has boosted #climat...,#India’s huge solar uptake has boosted #climat...,1456410876299329538,"{'_type': 'snscrape.modules.twitter.User', 'us...",0,0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"['India', 'climate', 'COP26']",NaN
3,snscrape.modules.twitter.Tweet,https://twitter.com/AsoPalabrasCl/status/14564...,2021-11-04 23:59:39+00:00,Reunión #COP26 Reunión mundial de países sobre...,Reunión #COP26 Reunión mundial de países sobre...,1456410848667348992,"{'_type': 'snscrape.modules.twitter.User', 'us...",0,0,0,...,NaN,NaN,"{'_type': 'snscrape.modules.twitter.Tweet', 'u...",NaN,NaN,NaN,NaN,NaN,"['COP26', 'AcuerdoDeParis', 'LenguajeClaro']",NaN
4,snscrape.modules.twitter.Tweet,https://twitter.com/Crstianst/status/145641082...,2021-11-04 23:59:35+00:00,@_pln_id PLN terdepan dukung pemanfaatan EBT🍃\...,@_pln_id PLN terdepan dukung pemanfaatan EBT🍃\...,1456410828974952480,"{'_type': 'snscrape.modules.twitter.User', 'us...",0,0,0,...,NaN,NaN,NaN,1.455825e+18,"{'_type': 'snscrape.modules.twitter.User', 'us...","[{'_type': 'snscrape.modules.twitter.User', 'u...",NaN,NaN,"['COP26', 'PLNGreen']",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7995,snscrape.modules.twitter.Tweet,https://twitter.com/AqsaYounasRana/status/1456...,2021-11-04 13:20:36+00:00,"ClimateChange is no more only a challenge, it’...","ClimateChange is no more only a challenge, it’...",1456250023923048453,"{'_type': 'snscrape.modules.twitter.User', 'us...",0,6,5,...,"[{'_type': 'snscrape.modules.twitter.Photo', '...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,"['Climate', 'ClimateAction', 'COP26', 'climate...",NaN
7996,snscrape.modules.twitter.Tweet,https://twitter.com/pete4peace/status/14562499...,2021-11-04 13:20:18+00:00,We confronted the coal baron this morning! Fuc...,We confronted the coal baron this morning! Fuc...,1456249951009320965,"{'_type': 'snscrape.modules.twitter.User', 'us...",0,0,3,...,NaN,NaN,"{'_type': 'snscrape.modules.twitter.Tweet', 'u...",NaN,NaN,NaN,{'_type': 'snscrape.modules.twitter.Coordinate...,"{'_type': 'snscrape.modules.twitter.Place', 'f...","['JoeManchin', 'JoeManchinSenatorForSale', 'Jo...",NaN
7997,snscrape.modules.twitter.Tweet,https://twitter.com/mmill_landscape/status/145...,2021-11-04 13:19:58+00:00,Feeling simply disgusted by countries such as ...,Feeling simply disgusted by countries such as ...,1456249866196226048,"{'_type': 'snscrape.modules.twitter.User', 'us...",0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"['china', 'usa', 'india', 'COP26Glasgow', 'Fos...",NaN
7998,snscrape.modules.twitter.Tweet,https://twitter.com/KarynCaplan/status/1456249...,2021-11-04 13:19:45+00:00,🚨 Join us in calling for @Google and #Facebook...,🚨 Join us in calling for @Google and #Facebook...,1456249809292177409,"{'_type': 'snscrape.modules.twitter.User', 'us...",0,0,0,...,NaN,NaN,"{'_type': 'snscrape.modules.twitter.Tweet', 'u...",NaN,NaN,"[{'_type': 'snscrape.modules.twitter.User', 'u...",NaN,NaN,"['Facebook', 'climatechange', 'disinformation'...",NaN
7999,snscrape.modules.twitter.Tweet,https://twitter.com/DrDuly/status/145624972696...,2021-11-04 13:19:25+00:00,"There is no doubt! ""The science is clear: to k...","There is no doubt! ""The science is clear: to k...",1456249726962073604,"{'_type': 'snscrape.modules.twitter.User', 'us...",0,0,0,...,NaN,NaN,NaN,NaN,NaN,"[{'_type': 'snscrape.modules.twitter.User', 'u...",NaN,NaN,"['COP26Glasgow', 'COP26', 'ClimateActionNow', ...",NaN

In [9]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7616 entries, 0 to 7999
Data columns (total 28 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   _type             7616 non-null   object
 1   url               7616 non-null   object
 2   date              7616 non-null   object
 3   content           7616 non-null   object
 4   renderedContent   7616 non-null   object
 5   id                7616 non-null   int64
 6   user              7616 non-null   object
 7   replyCount        7616 non-null   int64
 8   retweetCount      7616 non-null   int64
 9   likeCount         7616 non-null   int64
 10  quoteCount        7616 non-null   int64
 11  conversationId    7616 non-null   int64
 12  lang              7616 non-null   object
 13  source            7616 non-null   object
 14  sourceUrl         7616 non-null   object
 15  sourceLabel       7616 non-null   object
 16  outlinks          4437 non-null   object
 17  tcooutlinks       4437 non-null   object
 18  media             2500 non-null   object
 19  retweetedTweet    0 non-null      float64
 20  quotedTweet       1636 non-null   object
 21  inReplyToTweetId  1031 non-null   float64
 22  inReplyToUser     1031 non-null   object
 23  mentionedUsers    3428 non-null   object
 24  coordinates       235 non-null    object
 25  place             235 non-null    object
 26  hashtags          7616 non-null   object
 27  cashtags          19 non-null     object
dtypes: float64(2), int64(6), object(20)
memory usage: 1.7+ MB

### Dropping columns

In [10]:
df1_cols = list(df1.columns)

In [11]:
df1_clean_col = df1.copy()

In [12]:
df1_clean_col.shape

(7616, 28)

In [13]:
# dropping unnecessary columns 
df1_clean_col.drop(['_type', 'url','conversationId', 'lang', 'source', 'sourceUrl', 'sourceLabel','outlinks', 'tcooutlinks', 'media', 'retweetedTweet', 'quotedTweet',
       'inReplyToTweetId', 'inReplyToUser', 'mentionedUsers', 'coordinates',
       'place','cashtags'], axis=1, inplace=True)

In [14]:
df1_clean_col.head()

,date,content,renderedContent,id,user,replyCount,retweetCount,likeCount,quoteCount,hashtags
0,2021-11-04 23:59:50+00:00,@Banterm42404691 @MrHarryCole Absolutely one s...,@Banterm42404691 @MrHarryCole Absolutely one s...,1456410892422295556,"{'_type': 'snscrape.modules.twitter.User', 'us...",0,0,0,0,['COP26']
1,2021-11-04 23:59:48+00:00,"Please join us at a #COP26 side event ""Impleme...","Please join us at a #COP26 side event ""Impleme...",1456410883471523840,"{'_type': 'snscrape.modules.twitter.User', 'us...",0,1,2,1,['COP26']
2,2021-11-04 23:59:46+00:00,#India’s huge solar uptake has boosted #climat...,#India’s huge solar uptake has boosted #climat...,1456410876299329538,"{'_type': 'snscrape.modules.twitter.User', 'us...",0,0,1,0,"['India', 'climate', 'COP26']"
3,2021-11-04 23:59:39+00:00,Reunión #COP26 Reunión mundial de países sobre...,Reunión #COP26 Reunión mundial de países sobre...,1456410848667348992,"{'_type': 'snscrape.modules.twitter.User', 'us...",0,0,0,0,"['COP26', 'AcuerdoDeParis', 'LenguajeClaro']"
4,2021-11-04 23:59:35+00:00,@_pln_id PLN terdepan dukung pemanfaatan EBT🍃\...,@_pln_id PLN terdepan dukung pemanfaatan EBT🍃\...,1456410828974952480,"{'_type': 'snscrape.modules.twitter.User', 'us...",0,0,0,0,"['COP26', 'PLNGreen']"

In [15]:
df1_clean_col['content'][0]

'@Banterm42404691 @MrHarryCole Absolutely one self indulgent ego trip!! #COP26'

In [16]:
df1_clean_col[df1_clean_col['content'].isna()]

Empty DataFrame
Columns: [date, content, renderedContent, id, user, replyCount, retweetCount, likeCount, quoteCount, hashtags]
Index: []

In [17]:
df1_clean_col['user'][0]

"{'_type': 'snscrape.modules.twitter.User', 'username': 'aquitainexox', 'id': 4121071047, 'displayname': 'Lisa', 'description': 'Shits & Giggles', 'rawDescription': 'Shits & Giggles', 'descriptionUrls': None, 'verified': False, 'created': '2015-11-05T18:11:59+00:00', 'followersCount': 1126, 'friendsCount': 455, 'statusesCount': 35726, 'favouritesCount': 57877, 'listedCount': 9, 'mediaCount': 4620, 'location': 'UK: ', 'protected': False, 'linkUrl': None, 'linkTcourl': None, 'profileImageUrl': 'https://pbs.twimg.com/profile_images/1423390231831666689/CbwFIFHS_normal.jpg', 'profileBannerUrl': 'https://pbs.twimg.com/profile_banners/4121071047/1635524029', 'label': None, 'url': 'https://twitter.com/aquitainexox'}"

In [18]:
user_tweet_df =pd.DataFrame(columns=['user_id','tweet'])
#user_tweet_df.columns= ['user_id','tweet']

In [19]:
#s = list(df1_clean_col['user'])

In [20]:
#type(s)

In [21]:
#import ast
#s_1 = []
#for i in s:
    #s_1.append(ast.literal_eval(i))

In [22]:
#s_1

In [23]:
#s_1[0]['username']

In [24]:
#len(s_1)

In [25]:
#usernames = []
#for i in range(len(s_1)):
    #usernames.append(s_1[i]['username'])

In [26]:
#usernames

In [27]:
#len(usernames)

In [28]:
#len(df1_clean_col['content'])

In [29]:
df1_clean_col.columns

Index(['date', 'content', 'renderedContent', 'id', 'user', 'replyCount',
       'retweetCount', 'likeCount', 'quoteCount', 'hashtags'],
      dtype='object')

In [30]:
df_tw = df1_clean_col[['date','user','content','likeCount', 'quoteCount', 'hashtags']]

In [31]:
df_tw

,date,user,content,likeCount,quoteCount,hashtags
0,2021-11-04 23:59:50+00:00,"{'_type': 'snscrape.modules.twitter.User', 'us...",@Banterm42404691 @MrHarryCole Absolutely one s...,0,0,['COP26']
1,2021-11-04 23:59:48+00:00,"{'_type': 'snscrape.modules.twitter.User', 'us...","Please join us at a #COP26 side event ""Impleme...",2,1,['COP26']
2,2021-11-04 23:59:46+00:00,"{'_type': 'snscrape.modules.twitter.User', 'us...",#India’s huge solar uptake has boosted #climat...,1,0,"['India', 'climate', 'COP26']"
3,2021-11-04 23:59:39+00:00,"{'_type': 'snscrape.modules.twitter.User', 'us...",Reunión #COP26 Reunión mundial de países sobre...,0,0,"['COP26', 'AcuerdoDeParis', 'LenguajeClaro']"
4,2021-11-04 23:59:35+00:00,"{'_type': 'snscrape.modules.twitter.User', 'us...",@_pln_id PLN terdepan dukung pemanfaatan EBT🍃\...,0,0,"['COP26', 'PLNGreen']"
...,...,...,...,...,...,...
7995,2021-11-04 13:20:36+00:00,"{'_type': 'snscrape.modules.twitter.User', 'us...","ClimateChange is no more only a challenge, it’...",5,0,"['Climate', 'ClimateAction', 'COP26', 'climate..."
7996,2021-11-04 13:20:18+00:00,"{'_type': 'snscrape.modules.twitter.User', 'us...",We confronted the coal baron this morning! Fuc...,3,0,"['JoeManchin', 'JoeManchinSenatorForSale', 'Jo..."
7997,2021-11-04 13:19:58+00:00,"{'_type': 'snscrape.modules.twitter.User', 'us...",Feeling simply disgusted by countries such as ...,0,0,"['china', 'usa', 'india', 'COP26Glasgow', 'Fos..."
7998,2021-11-04 13:19:45+00:00,"{'_type': 'snscrape.modules.twitter.User', 'us...",🚨 Join us in calling for @Google and #Facebook...,0,0,"['Facebook', 'climatechange', 'disinformation'..."
7999,2021-11-04 13:19:25+00:00,"{'_type': 'snscrape.modules.twitter.User', 'us...","There is no doubt! ""The science is clear: to k...",0,0,"['COP26Glasgow', 'COP26', 'ClimateActionNow', ..."

In [32]:
df_tw['user_lst'] = list(df_tw['user'])

<ipython-input-32-f4a3887ba62a>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_tw['user_lst'] = list(df_tw['user'])

In [33]:
df_tw['user_lst']

0       {'_type': 'snscrape.modules.twitter.User', 'us...
1       {'_type': 'snscrape.modules.twitter.User', 'us...
2       {'_type': 'snscrape.modules.twitter.User', 'us...
3       {'_type': 'snscrape.modules.twitter.User', 'us...
4       {'_type': 'snscrape.modules.twitter.User', 'us...
                              ...
7995    {'_type': 'snscrape.modules.twitter.User', 'us...
7996    {'_type': 'snscrape.modules.twitter.User', 'us...
7997    {'_type': 'snscrape.modules.twitter.User', 'us...
7998    {'_type': 'snscrape.modules.twitter.User', 'us...
7999    {'_type': 'snscrape.modules.twitter.User', 'us...
Name: user_lst, Length: 7616, dtype: object

In [34]:
import ast
df_tw['column_2'] = df_tw['user_lst'].apply(lambda x: ast.literal_eval(str(x)))

<ipython-input-34-bf4cc193b73b>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_tw['column_2'] = df_tw['user_lst'].apply(lambda x: ast.literal_eval(str(x)))

In [35]:
df_tw['column_2'][0]['username']

'aquitainexox'

In [36]:
len(df_tw['column_2'])

7616

In [37]:
df_tw

,date,user,content,likeCount,quoteCount,hashtags,user_lst,column_2
0,2021-11-04 23:59:50+00:00,"{'_type': 'snscrape.modules.twitter.User', 'us...",@Banterm42404691 @MrHarryCole Absolutely one s...,0,0,['COP26'],"{'_type': 'snscrape.modules.twitter.User', 'us...","{'_type': 'snscrape.modules.twitter.User', 'us..."
1,2021-11-04 23:59:48+00:00,"{'_type': 'snscrape.modules.twitter.User', 'us...","Please join us at a #COP26 side event ""Impleme...",2,1,['COP26'],"{'_type': 'snscrape.modules.twitter.User', 'us...","{'_type': 'snscrape.modules.twitter.User', 'us..."
2,2021-11-04 23:59:46+00:00,"{'_type': 'snscrape.modules.twitter.User', 'us...",#India’s huge solar uptake has boosted #climat...,1,0,"['India', 'climate', 'COP26']","{'_type': 'snscrape.modules.twitter.User', 'us...","{'_type': 'snscrape.modules.twitter.User', 'us..."
3,2021-11-04 23:59:39+00:00,"{'_type': 'snscrape.modules.twitter.User', 'us...",Reunión #COP26 Reunión mundial de países sobre...,0,0,"['COP26', 'AcuerdoDeParis', 'LenguajeClaro']","{'_type': 'snscrape.modules.twitter.User', 'us...","{'_type': 'snscrape.modules.twitter.User', 'us..."
4,2021-11-04 23:59:35+00:00,"{'_type': 'snscrape.modules.twitter.User', 'us...",@_pln_id PLN terdepan dukung pemanfaatan EBT🍃\...,0,0,"['COP26', 'PLNGreen']","{'_type': 'snscrape.modules.twitter.User', 'us...","{'_type': 'snscrape.modules.twitter.User', 'us..."
...,...,...,...,...,...,...,...,...
7995,2021-11-04 13:20:36+00:00,"{'_type': 'snscrape.modules.twitter.User', 'us...","ClimateChange is no more only a challenge, it’...",5,0,"['Climate', 'ClimateAction', 'COP26', 'climate...","{'_type': 'snscrape.modules.twitter.User', 'us...","{'_type': 'snscrape.modules.twitter.User', 'us..."
7996,2021-11-04 13:20:18+00:00,"{'_type': 'snscrape.modules.twitter.User', 'us...",We confronted the coal baron this morning! Fuc...,3,0,"['JoeManchin', 'JoeManchinSenatorForSale', 'Jo...","{'_type': 'snscrape.modules.twitter.User', 'us...","{'_type': 'snscrape.modules.twitter.User', 'us..."
7997,2021-11-04 13:19:58+00:00,"{'_type': 'snscrape.modules.twitter.User', 'us...",Feeling simply disgusted by countries such as ...,0,0,"['china', 'usa', 'india', 'COP26Glasgow', 'Fos...","{'_type': 'snscrape.modules.twitter.User', 'us...","{'_type': 'snscrape.modules.twitter.User', 'us..."
7998,2021-11-04 13:19:45+00:00,"{'_type': 'snscrape.modules.twitter.User', 'us...",🚨 Join us in calling for @Google and #Facebook...,0,0,"['Facebook', 'climatechange', 'disinformation'...","{'_type': 'snscrape.modules.twitter.User', 'us...","{'_type': 'snscrape.modules.twitter.User', 'us..."
7999,2021-11-04 13:19:25+00:00,"{'_type': 'snscrape.modules.twitter.User', 'us...","There is no doubt! ""The science is clear: to k...",0,0,"['COP26Glasgow', 'COP26', 'ClimateActionNow', ...","{'_type': 'snscrape.modules.twitter.User', 'us...","{'_type': 'snscrape.modules.twitter.User', 'us..."

In [38]:
df_tw = df_tw.reset_index(drop=True)

In [39]:
df_tw

,date,user,content,likeCount,quoteCount,hashtags,user_lst,column_2
0,2021-11-04 23:59:50+00:00,"{'_type': 'snscrape.modules.twitter.User', 'us...",@Banterm42404691 @MrHarryCole Absolutely one s...,0,0,['COP26'],"{'_type': 'snscrape.modules.twitter.User', 'us...","{'_type': 'snscrape.modules.twitter.User', 'us..."
1,2021-11-04 23:59:48+00:00,"{'_type': 'snscrape.modules.twitter.User', 'us...","Please join us at a #COP26 side event ""Impleme...",2,1,['COP26'],"{'_type': 'snscrape.modules.twitter.User', 'us...","{'_type': 'snscrape.modules.twitter.User', 'us..."
2,2021-11-04 23:59:46+00:00,"{'_type': 'snscrape.modules.twitter.User', 'us...",#India’s huge solar uptake has boosted #climat...,1,0,"['India', 'climate', 'COP26']","{'_type': 'snscrape.modules.twitter.User', 'us...","{'_type': 'snscrape.modules.twitter.User', 'us..."
3,2021-11-04 23:59:39+00:00,"{'_type': 'snscrape.modules.twitter.User', 'us...",Reunión #COP26 Reunión mundial de países sobre...,0,0,"['COP26', 'AcuerdoDeParis', 'LenguajeClaro']","{'_type': 'snscrape.modules.twitter.User', 'us...","{'_type': 'snscrape.modules.twitter.User', 'us..."
4,2021-11-04 23:59:35+00:00,"{'_type': 'snscrape.modules.twitter.User', 'us...",@_pln_id PLN terdepan dukung pemanfaatan EBT🍃\...,0,0,"['COP26', 'PLNGreen']","{'_type': 'snscrape.modules.twitter.User', 'us...","{'_type': 'snscrape.modules.twitter.User', 'us..."
...,...,...,...,...,...,...,...,...
7611,2021-11-04 13:20:36+00:00,"{'_type': 'snscrape.modules.twitter.User', 'us...","ClimateChange is no more only a challenge, it’...",5,0,"['Climate', 'ClimateAction', 'COP26', 'climate...","{'_type': 'snscrape.modules.twitter.User', 'us...","{'_type': 'snscrape.modules.twitter.User', 'us..."
7612,2021-11-04 13:20:18+00:00,"{'_type': 'snscrape.modules.twitter.User', 'us...",We confronted the coal baron this morning! Fuc...,3,0,"['JoeManchin', 'JoeManchinSenatorForSale', 'Jo...","{'_type': 'snscrape.modules.twitter.User', 'us...","{'_type': 'snscrape.modules.twitter.User', 'us..."
7613,2021-11-04 13:19:58+00:00,"{'_type': 'snscrape.modules.twitter.User', 'us...",Feeling simply disgusted by countries such as ...,0,0,"['china', 'usa', 'india', 'COP26Glasgow', 'Fos...","{'_type': 'snscrape.modules.twitter.User', 'us...","{'_type': 'snscrape.modules.twitter.User', 'us..."
7614,2021-11-04 13:19:45+00:00,"{'_type': 'snscrape.modules.twitter.User', 'us...",🚨 Join us in calling for @Google and #Facebook...,0,0,"['Facebook', 'climatechange', 'disinformation'...","{'_type': 'snscrape.modules.twitter.User', 'us...","{'_type': 'snscrape.modules.twitter.User', 'us..."
7615,2021-11-04 13:19:25+00:00,"{'_type': 'snscrape.modules.twitter.User', 'us...","There is no doubt! ""The science is clear: to k...",0,0,"['COP26Glasgow', 'COP26', 'ClimateActionNow', ...","{'_type': 'snscrape.modules.twitter.User', 'us...","{'_type': 'snscrape.modules.twitter.User', 'us..."

In [40]:
df_tw['column_2'][0]

{'_type': 'snscrape.modules.twitter.User',
 'username': 'aquitainexox',
 'id': 4121071047,
 'displayname': 'Lisa',
 'description': 'Shits & Giggles',
 'rawDescription': 'Shits & Giggles',
 'descriptionUrls': None,
 'verified': False,
 'created': '2015-11-05T18:11:59+00:00',
 'followersCount': 1126,
 'friendsCount': 455,
 'statusesCount': 35726,
 'favouritesCount': 57877,
 'listedCount': 9,
 'mediaCount': 4620,
 'location': 'UK: ',
 'protected': False,
 'linkUrl': None,
 'linkTcourl': None,
 'profileImageUrl': 'https://pbs.twimg.com/profile_images/1423390231831666689/CbwFIFHS_normal.jpg',
 'profileBannerUrl': 'https://pbs.twimg.com/profile_banners/4121071047/1635524029',
 'label': None,
 'url': 'https://twitter.com/aquitainexox'}

In [41]:
del df_tw['user']

In [42]:
del df_tw['user_lst']

In [43]:
twitter_id  = []
for i in range(len(df_tw['column_2'])):
    twitter_id.append(df_tw['column_2'][i]['username'])

In [44]:
twitter_id

['aquitainexox',
 'GEC_JCM_Info',
 'zpnine',
 'AsoPalabrasCl',
 'Crstianst',
 'PGDynes',
 'UNAI_mx',
 'Xplorit',
 'SEforALLorg',
 'quitoriskhub',
 'quitoriskhub',
 'TransformaGlob',
 'OwlHoot16',
 'Trina1913',
 'ArchbishopEamon',
 'chrisB_oz',
 'EduSanchezAnaya',
 'GEN_Ecovillages',
 'anasalhajji',
 'tocsasolutions',
 'WatchTowerGW',
 'Trina1913',
 'SkyNews',
 'Diplomacy140',
 'EEGResearch',
 'ThibautLugagne',
 'ModernSociety33',
 'theserfstv',
 'ChalecosAmarill',
 'Crstianst',
 'MGN31',
 'PrimeraPlanaECU',
 'ajch041',
 'arcatierraint',
 'welshroots',
 'Eming_Tiger',
 'xxdbzczl',
 'bubanjuglord',
 'arcatierraint',
 'NEG4TORY',
 'vidasimples',
 'barryjohnharper',
 'bretonsdujapon',
 'marinadpol',
 'pseanmc',
 'manishsjoshi',
 'LisolarkKoncept',
 'JenniferTweep',
 'DegiorgioElaine',
 'Tripudiante',
 'clau_eas',
 'superchemist13',
 'WVycE4esUiIOUXk',
 'VasquezLuisE',
 'rodnergimenez',
 'MikeHMMT',
 'madhavanpallan',
 'irene89383961',
 'GregGraziano',
 'RochelleVincent',
 'TimAshburner',
 'AldanaLeonorPV',
 'MaiSutherland',
 'energyvoiceau',
 'Crstianst',
 'FBacumen',
 'vidasimples',
 'torontolabour',
 'linzisueboo',
 'UkiLifeAbroad',
 'solarcookersint',
 'WildRoseEducate',
 'chriscartw83',
 'Daily_Express',
 'vidasimples',
 'robmpow83',
 'Perssonasa',
 'saf0113',
 'thomaslingard',
 'rlvmuller',
 'kevinadiamond',
 'evlyncervantes',
 'macroymercados',
 'missuan',
 'FriendsofEbA',
 'talkimhangar7',
 'jmblgr',
 'vidasimples',
 'SmeeHereAgain',
 'cfschaer',
 'vidasimples',
 'skelly1178',
 'SmiKooMan',
 'happymonkey1874',
 'BrianAllman',
 'vidasimples',
 'DEM_sagov',
 'reid_more',
 'AFCA_Forests',
 'frazz82',
 'robmpow83',
 'Crstianst',
 'WaltonDesousa',
 'Perssonasa',
 'c_pdesrosiers',
 'richard35609781',
 'PFCtweet1',
 'TRF_Climate',
 'JULIOARNALDES',
 'FerGerAin1',
 'respectatworkuk',
 'FloatLikeAstar',
 'IvaniGreppi',
 'AnsaldoVernica',
 'stop4nowt',
 'ClimateLatino',
 'ukiswitheu',
 'safbf',
 'safbf',
 'FavourJ93174111',
 'MLiebreich',
 'vidasimples',
 'LuchoDiaz12',
 'LuchoDiaz12',
 'FawnJackson1',
 'marianabelmont',
 'happymonkey1874',
 'keithmartinmd',
 'delphnews',
 'coalizaonegra',
 'MontyLabour',
 'AuEpochTimes',
 'quakes99',
 'nickhobson25',
 'FernandaCamino',
 'andreuqs',
 'PFCtweet1',
 'CspoWatch',
 'DrJonathanCobb',
 'MikeDKwine',
 'AllansGray',
 'AllansGray',
 'robmpow83',
 'oliver_phil',
 'zeroxcliche',
 'linzisueboo',
 'ilenviro',
 'charlp27',
 'LizWainwright',
 'fbpe_h',
 'Lucy__Byford',
 'SRadiocreate',
 'robmpow83',
 'FlowNews24',
 'FundacionMERI',
 'sinnemanie',
 'fernandoossa',
 'Tina_Faiz',
 'alan_poirier',
 'Emiliecoquard',
 'JuanInhamagua',
 'ProfessorChook',
 'AShields_Devoir',
 'richard35609781',
 'DaiGoch',
 'bastardsheep',
 'MsCynMet',
 'Zangiff',
 'mylilblkangel',
 'Inhumansoflate1',
 'Katy08215021',
 'PFCtweet1',
 'BrianMcHugh2011',
 'franciscoreyes',
 'centralspotter',
 'MOEPPMKD',
 'agenciajovem_',
 'talkimhangar7',
 'CRL_UK',
 'Zangiff',
 'buckleup',
 'montrealsimon',
 'GargajoVaginal_',
 'Citizen4Sustain',
 'catherine___c',
 'LouisianaGov',
 'LouisianaGov',
 'LouisianaGov',
 'RickJoh44846997',
 'Jems1001',
 'SamGRuta',
 'isa_beloa',
 'WillMartinUK',
 'SharronWardTV',
 'Scot_Scientist',
 'G_Communities',
 'ncelenviro',
 'josephpallant',
 'CoralCoE',
 'SmokeSignalBR',
 'YnelUbaldo',
 'WassimMuna',
 'RolandGruner',
 'DavidStrathMc',
 'extrapolate1',
 'timb_89',
 'brianabombana',
 'magwitch5151',
 'Dr_Larouche',
 'BooandJerry',
 'satomi_i930',
 'randomhuman1999',
 'AldanaLeonorPV',
 'AmSysNow',
 'unicefaustralia',
 'IsabelleLHriti1',
 'StorageNinja',
 'BU_Research',
 'BooandJerry',
 'FRIDAfund',
 'dw_espanol',
 'SvenFrontin',
 'hutchesonglenn',
 'mentalbeeings',
 'BooandJerry',
 'danavitarte',
 'carsinogenic',
 'AhrcHeritage',
 'richard35609781',
 'OhmarieCS',
 'ShivajiShivaLaw',
 'memosquera',
 'UNDPinPNG',
 'LauryAnnne',
 'cherry_weed',
 'LauraBe36550188',
 'quakes99',
 'RESCUEorg',
 'nicobaudon',
 'GalvarengaG',
 'jmeferrell',
 'CheboluVasantha',
 'TIAflashcards',
 'HPE_News',
 'DanJCass',
 'ListenSport',
 'NiemLaura',
 'claire_rhiannon',
 'CarbonoNeutralC',
 'williamstablef1',
 'zelfstudie',
 'edgarrmcgregor',
 'EnriqueAlfaroR',
 'CheboluVasantha',
 'JDominguez_B',
 'VisionAmazonia',
 'patrin',
 'FHURRACA',
 'paramosybosques',
 'AloisGallet',
 'PactEnvironment',
 'Brain_Chain',
 'b_berx',
 'centralspotter',
 'Dora56191210',
 'EduSanchezAnaya',
 'TheAusInstitute',
 'AgendaMali',
 'oliver_phil',
 'CheboluVasantha',
 'ShelleyWood2',
 'Ekklesia_co_uk',
 'Fiilgueiras',
 'Synergia_AP',
 'RCDagle',
 'blondic69',
 'EuclidesNetoRJ',
 'TweetsBentley',
 'ineschalvarez1',
 'Franzish',
 'guitarwombat',
 'talkimhangar7',
 'clearloopUS',
 'oncleanair',
 'b_berx',
 'guitarwombat',
 'SRadiocreate',
 'carsinogenic',
 'CarolineChoi',
 'Ekklesia_co_uk',
 'AmbMacArthur',
 'diariARA',
 'gabrielfidel',
 'Dep_Sustentable',
 'MarthaIGuzman',
 'SILVANAFLORESC1',
 'KAGABAIsaacJr',
 'anton_polaiap',
 'CheboluVasantha',
 'MattDDobson',
 'GrataFund',
 'PugetSoundSolar',
 'Slugslime2',
 'FoxiePunkFolk',
 'Ilias_Energia',
 'support_ev',
 'CarbonVerse',
 'Cha_Minvielle',
 'duda_zoghbi',
 'richard35609781',
 'OnebyOneBristol',
 'trent_lewin',
 'monchingonzalez',
 'Talya',
 'alan_poirier',
 'skyeecl',
 'MontseSalazarGa',
 'JaneLubchenco46',
 'France24_es',
 'TheAESCorp',
 'CEMSecretariat',
 'hmarston4',
 'DoodlebugKRY',
 'SenJoshBecker',
 'kouzie01',
 'amigosRSV',
 '2021boilingfrog',
 'clare_m_cooper',
 'zelfstudie',
 'TIAflashcards',
 'cityofselkirk',
 'MMikulewicz',
 'bedarumica',
 'tleurent',
 'heatherleah',
 'vasanti_hd',
 'TruthFairyLand',
 'timbaland57',
 'Mark_A_Goddard',
 'ClimateJobList',
 'ECOWARRIORSS',
 'ukiswitheu',
 'MariaARiv',
 'ginamccarthy46',
 'StillGame30',
 'rodriguez_magie',
 'ochaye1934',
 'wavetop',
 'MatthewLipson',
 'fidh_es',
 'dw_espanol',
 'McmackinRoisin',
 'millicent_barty',
 'Fact_Oracle',
 'leftboomer',
 'Diplomacy140',
 'RockyMtnInst',
 'UNAI_mx',
 'sujalnitdgp',
 'simonplewis',
 'FUTURENEWS2020',
 'CheboluVasantha',
 'leadingforkids',
 'OlumideIDOWU',
 'LightRider59',
 'nishiyamakimita',
 'ShropshireSBM',
 'labcddelapolit1',
 'EUribarren',
 'undrr_pacific',
 'dianavaneyk',
 'PA_LatinAmerica',
 'EvanKirstel',
 'jenstirrup',
 'quitoriskhub',
 'OnyaDon',
 'Lothar_Xanadu',
 'quitoriskhub',
 'gordanaOz',
 'catherinebanet',
 'leftboomer',
 'gnsscience',
 'BelindaCoates',
 'fidh_es',
 'jewishsf',
 'MeteoredAR',
 'Sipremo_oficial',
 'richard35609781',
 'JoshBeckerSV',
 'IsraelinMexico',
 'AldanaLeonorPV',
 'TIAflashcards',
 'MarineLog',
 'h2_view',
 'leftboomer',
 'Da_Clemens',
 'juancabandie',
 'bencaudron',
 'veillelgbt',
 'AloisGallet',
 'smartkiwis',
 'CiceronSevilla',
 'MelissaSweetDr',
 'LouiseT40665028',
 'Imen_C',
 'centralspotter',
 'VoicelessName',
 'WeakyLynam',
 'WithyGrove',
 'leftboomer',
 'AgilYosi',
 'MunkSimon',
 'SergeiBRO',
 'FranceenCoree',
 'guitarwombat',
 'leegrace185',
 'MaraDolan1',
 'smakhanian',
 'SenJoshBecker',
 'newglasgowsoc',
 'aprektor',
 'jamesdoleman',
 'isabel_serra',
 'GregVezina',
 'LorrTighe',
 'luckyabeng',
 'AustCCR',
 'BrindusaB1',
 'cmm_morais',
 'talkimhangar7',
 'ararauna_ve',
 'palyugo',
 'TheLastPersont2',
 'cassouman40',
 'magwitch5151',
 'AlviroPatterson',
 'MikeCline8',
 'Channel6Reem',
 'MikeHudema',
 'UViCIVE',
 'ochaye1934',
 'perennialsandra',
 'dama_gallardo',
 'funlaughangel',
 'stephentrew',
 'julian_aang',
 'pa_Sanchez_1978',
 'SciTJC',
 'JLL_Guy',
 'smbilodeau',
 'AgilYosi',
 'centralspotter',
 'thdanvers',
 'AssoJNE',
 'ferayqui',
 'karenmahon',
 'oileral',
 'dama_gallardo',
 'TIAflashcards',
 'im_silverfox',
 'DamianPayne1',
 'Knuthov',
 'gburgham',
 'BayMarq',
 'StopMoneyPipe',
 'bidbr',
 'amonestadores',
 'ms4cy',
 'ScotPolTalk',
 'javiercorcuera',
 'runofthemilne',
 'pndblog',
 'divisionorderuk',
 'Japan_EY',
 'GlobalLF_Esp',
 'IFADespanol',
 'SgkPlanet_en',
 'VOAChinese',
 'BTnewsroom',
 'PromoMusic_it',
 'ineschalvarez1',
 'VarietyGuy2',
 'jeanneyacoubou',
 'CIFOR_bosques',
 'JoanitaBabirye',
 'seawildearth',
 'Channel6Reem',
 'kirstyloukirby',
 'axelsegebrecht',
 'NomadandSettler',
 'ms_kitka',
 'david_avien',
 'CandlemakerRow',
 'judyhorn13',
 'funlaughangel',
 'Marhurtadoramos',
 'kristianleth',
 'JaneLubchenco46',
 'freeseenice',
 'Gekko_au',
 'TymlezBV',
 'Jackthelad1947',
 'YkdOfficial',
 'mongrainle',
 'vidasimples',
 '4410powder',
 'BabsSheKing',
 'MySter_Brun_s',
 'fame_monte',
 'ThomasReeseSJ',
 'GreenEnergySca1',
 'sallyeaves',
 'william3150',
 'pradip808',
 'ShropshireSBM',
 'leftboomer',
 'danielediegidio',
 'grantjmcd',
 'fame_monte',
 'AbidGangatPR',
 'ValoisAngelo',
 'nekGMM',
 'KucingKuncitara',
 'mkent9900',
 'DankerSophia',
 'MiguelCabre_',
 'OscarDussan',
 'milnekrista',
 'wordwhisperer',
 'SmokeSignalBR',
 'Reforma',
 'B52Malmet',
 'Edu_cardoso87',
 'ConnieB_PFT',
 'YebSano',
 'heat_ondan',
 'ENGIENorthAm',
 'FLEXjs',
 'KelliGeeBee',
 'mrsnaveed03',
 'APEN4EJ',
 'pavzqzo',
 'LWV_UN_Climate',
 'GlobalGoalsUN',
 'rethink_nic',
 'Vaneemberracada',
 'Petchary',
 'ochaye1934',
 'ENGIENorthAm',
 'Duas_Revival',
 'anasalhajji',
 'DocsEnvAus',
 'allan_pollock',
 'EWThailand',
 'fame_monte',
 'KateEBrandt',
 'fame_monte',
 'HayleyJary',
 'gbc123',
 'Marhurtadoramos',
 'robertjgardner',
 'WorkinMom3Sons',
 'vidasimples',
 'tinforest',
 'TelestoStrategy',
 'johncreedon',
 'guitarwombat',
 'wordwhisperer',
 'FreshEnergy',
 'CETACanada',
 'TelestoStrategy',
 'mountainkeeper',
 'DecioMachadoF',
 'xrsouthsea',
 'catalanjock',
 'sfiemt',
 'anasalhajji',
 'UKinBolivia',
 'Ruminahui1973',
 'wgagnon',
 'AngusMacNeilSNP',
 'Channel6Reem',
 'vidasimples',
 'DindaSylwa',
 'manolito_garci',
 'Jason_Ribeiro',
 'Yuh_artisan',
 'brucekenneway',
 'AntonioGarciatv',
 'DnAArchitects',
 'mescriva',
 'gmh_2068',
 'anasalhajji',
 'globalpilgrim',
 'vidasimples',
 'TheLastPersont2',
 'Hemry',
 'WWF_LAC',
 '13sealite',
 'algiuf',
 'DietherAst',
 'CwHumanEcology',
 'ChristinsQueens',
 'scottdegg',
 'standardnews',
 'smbilodeau',
 'GreenEnergySca1',
 'LWV_UN_Climate',
 'yutaro_tamura',
 'SombreGreen',
 'ceskoo_cz',
 'tomkucharz',
 'dlanor2208',
 'MarketFOIL',
 'LatinReporters',
 'LeeFergusson',
 'ken1007tpgcoma1',
 'TinoPfaff',
 'raymasseytweets',
 'niklashoehne',
 'PrensaLatina_cu',
 'AlanRyuji1',
 'DDMexico',
 'FernandaVdeC',
 'mrsverypicky',
 'DrAnnaChavez',
 'gorbalsgoebbels',
 'lisduarte',
 'ShahrarAli',
 'AbidGangatPR',
 'RubieKerepa',
 'vidasimples',
 'World_Wildlife',
 'beatrizdiniz',
 'dhruvboruah',
 'SsoAclimate',
 'BLAIMGame',
 'Big_Jules',
 'm__brownfield',
 'Chris_SeedGH',
 'Ecogeographers',
 'Rachel__Sarah',
 'seatedwarrior',
 'arabnews',
 'Sdg7Youth',
 'centralspotter',
 'TheLastPersont2',
 'Northern_Acc',
 'DavidMMcEvoy',
 'FloraParkin',
 'wordwhisperer',
 'adeduntan',
 'eltiempolatino',
 'mainichikagaku',
 '15minutosUSA',
 'chriscartw83',
 'PiratePUKMaria',
 'LWV_UN_Climate',
 'flatulenceverte',
 'UTECuniversidad',
 'Dr_Days',
 'SianHarris8',
 'brickliterary',
 'carsinogenic',
 '_Ungagged',
 'BLAIMGame',
 'HippBilly',
 'WorldPeaceDayB1',
 'cen_climatenews',
 'IzabelManoli7',
 'JTweedie',
 'globalpilgrim',
 'Excocet',
 'JHerrera_2018',
 'postcarbon',
 'Rousquilles66',
 'funlaughangel',
 'ochaye1934',
 'SianTMmakeup',
 'EsperanzaCafe',
 'davva23',
 'Naturelcd',
 'Steve_Media',
 'CoeurniciaM',
 'nighthawkins',
 'onetotwo',
 'Scot_Scientist',
 'Jayson_Bryant',
 'LoLetters',
 'namaha_official',
 'BLAIMGame',
 'LeonieBremer1',
 'Sari_Official',
 'ManuelMosteyrin',
 'marlon_webbc',
 'talkimhangar7',
 'carlinds_',
 'CameronAMackay',
 'JorgeLWolpert',
 'Andresvi17',
 'andrewleedaly',
 'annaberu',
 'apple1910',
 'GeorgieAlbrun',
 'RogueSailor',
 'Ecogeographers',
 'helenhayes_',
 'CFAFCA',
 'RachelBendayan',
 'AndiKaraboutis',
 'NRDC',
 'ADixon_WB',
 'LucyGeraghty18',
 'RachelBendayan',
 'TK2262',
 'richardheinberg',
 'Sdg7Youth',
 'harmsy',
 'rosierawle',
 'DefOFaith',
 'seaparkin',
 'crossleyheath',
 'edking_I',
 'ReutersScience',
 'dsengeh',
 'heat_ondan',
 'synekzfamiloka',
 'jimicullenmusic',
 'nancysuzyq',
 'DindaSylwa',
 'Przemyslaw_Stef',
 'kate_harrisson',
 'drzax',
 'asuglobalfuture',
 'vidasimples',
 'ppokneb',
 'NRDC',
 'NRDC',
 'paulrogers002',
 'Julie_Hiromoto',
 'PeterWilson',
 'Deanidoo',
 'DasMeghna',
 'ConexionCop',
 'ProfStrachan',
 'julian_aang',
 'el_BID',
 'pfvalentino',
 'ms_kitka',
 'RuleWatcher',
 'jorgeangelgarc5',
 'stopclot',
 'wordwhisperer',
 'kouzie01',
 'AbidGangatPR',
 'BMHayward',
 'PatrickScientis',
 '1t_org_US',
 'Ecogeographers',
 'JacobsConnects',
 'PortAmbiental',
 'PuenteAereo1',
 'ScotExpress',
 'ecointeligencia',
 'alanros78250770',
 'wordwhisperer',
 'chelseaboy1972',
 'bloom_phillipa',
 'UCNZ',
 'Hannah_Bananaz',
 'ambienteysoc',
 'AnnaKernahan',
 'Greekboy8',
 'AnnHopcyn',
 'tonireid14',
 'UKinColombia',
 'seaelectricev',
 'pmagn',
 'adamrbruce',
 'wwfbrasil',
 'MILPA_climatica',
 'DRoss215',
 'WH_Welcomes',
 'staff_students',
 'HP48SX',
 'tkeizer',
 'DindaSylwa',
 'AvidMCentral',
 'RudyHavenstein',
 'non_size',
 'SamanthaLibreri',
 'sophiabotha74',
 'MikeShaugh',
 'Kanookandchook',
 'RachnaLeveque',
 'FckTheTories21',
 'Bayu643791315',
 'TheLastPersont2',
 'plant_ecologist',
 'TravellingAgro',
 'lemson84',
 'adebotes',
 'BrendanBehanN1',
 'FloraParkin',
 'AnyaMarchenko6',
 'DietherAst',
 'LaudatoSiMvmt',
 'ShahrarAli',
 'OlumideIDOWU',
 'mr_davidmacias',
 'Alistair_Pitts',
 'esimeat',
 'KellerZoe',
 'ja_salcedo',
 'asuglobalfuture',
 'carogilposse',
 'PFloppe',
 'DocsEnvAus',
 'Hammerman99',
 'vidasimples',
 'RawEchoesDJs',
 'ChrisWerner_WL3',
 'Angel_ULiege',
 'rcg_media',
 'stephengoldie',
 'RSHMNGO',
 'gorbalsgoebbels',
 'StephenMcMurray',
 'NickHartley',
 'Channel6Reem',
 'TerraPress',
 'MomentumMag',
 'TaisGadeaLara',
 'Channel6Reem',
 'howard_lang1',
 'laurentsamuel',
 'MarkHazard2020',
 'andrewleedaly',
 'OlumideIDOWU',
 'Marcio_L_O',
 'fabiocapitanio2',
 'Irreverent_B',
 'green_ecuador',
 'leapthecrowd',
 'orosane',
 'hhedgedd',
 'TwistedKelpie',
 'ES_Faulkner',
 'elespectador',
 'Excocet',
 'AbidGangatPR',
 'rachcsteele',
 'AppVeggly',
 'ReutersLatam',
 'lulinspector',
 'PennyBurdett',
 'ShahrarAli',
 'al3x_thoma5',
 'IOweYouN0thing',
 'deborah_hilliam',
 'biocarbono_',
 'randalgwturner',
 'ineschalvarez1',
 'AcnuUnaCuba',
 'KerryeagleMee',
 'SustainAllLife',
 'CheaperBuyMiles',
 'Nabukeera',
 'BabsSheKing',
 'MatthewMahabadi',
 'paulrogers002',
 'fame_monte',
 'PunkBiologist',
 'remblance_erin',
 'flightdekker',
 'GeoffBrewer',
 'JaspersPhilipp',
 'Bisont3',
 'SciDevNet_AL',
 'CounsellorNLond',
 'TerraPress',
 'DrTamsinBlack',
 'RollingStoneCol',
 'jekoranium',
 'resistance2030',
 'UKinFlorida',
 'FroioAnna',
 'SilingWu',
 'ClaudiaDobles',
 'ProfPMiddleton',
 'TheLastPersont2',
 'BatrasStavros',
 '1t_org_US',
 'BatrasStavros',
 'RaghnallD',
 'UNIC_Tokyo',
 'WalterEormotiv',
 'mal675',
 'YebSano',
 'RelentlessReese',
 'Agrannywhosaid1',
 'gpiDhLJzxNuAkzk',
 'mario_campa',
 'Krista_SC',
 'FizziCool',
 'eulalia_choque',
 'SharaiJoseph',
 'AlokSharma_RDG',
 'curaezipirid',
 'ArpinBel',
 'paulrogers002',
 'sophiabotha74',
 'Emilia_Equidad',
 'ISmokyand',
 'alfredogalvezb',
 'jeanneyacoubou',
 'UChiPolitics',
 'teriin',
 'DancingDanB',
 'StephenMedlock5',
 'fame_monte',
 'socialggf',
 'MessinaSergio',
 'GerComiskey',
 'CIenPeru',
 'MatthewMahabadi',
 'WGC_Climate',
 'wh0n0z',
 'FundGoRound',
 'AbidGangatPR',
 'cktweeet',
 'ECOWARRIORSS',
 'alexgill',
 'GPforEducation',
 'LaurenSCochran',
 'moreblock19',
 'RickOShea54321',
 'GonzaLib1853',
 'OrchowskiThomas',
 'JuandelosZorros',
 'atlantawatl',
 'paulrogers002',
 'centralspotter',
 'blakandblack',
 'milkastepien',
 'esimeat',
 'UNBiodiversity',
 'ozrevive',
 'FoodAgFitz',
 'KCTDUHO',
 'Malia_Forner',
 'YebSano',
 'gayako2',
 'lewisgarland',
 'ChristopherNFox',
 'Uptheleft',
 'ProfStrachan',
 'svdp_school',
 'AlanHayes28',
 'intomoderntimes',
 'centralspotter',
 'OutspokenSphere',
 'albertfortruth',
 'infoweltnews',
 'mentalbeeings',
 'njquin',
 'cceenergia',
 'arbzoid',
 'KLM412',
 'StopMoneyPipe',
 'DrSimEvans',
 'HELLANBL',
 'internetchris',
 'Knighte11253512',
 'gurrupletos',
 'happymonkey1874',
 'marcelopatrizi',
 'GeraldKutney',
 'Naturelcd',
 'blues155',
 'fame_monte',
 'IMariashikongo',
 'ICRAF',
 'BuggieWhips',
 'ECOWARRIORSS',
 'MarkHazard2020',
 'Vanwheel',
 'bjverschoor',
 'newsoneplace',
 'robynkelly67',
 'aguaorgmx',
 'UNFCCC',
 'happymonkey1874',
 'standardnews',
 'sophiabotha74',
 'WizBish',
 'TonyDowling',
 'fogaratigh',
 'MayaLillianM',
 'marie_sherlock',
 ...]

In [45]:
df_tw['twitter_id'] = twitter_id

In [46]:
df_tw

,date,content,likeCount,quoteCount,hashtags,column_2,twitter_id
0,2021-11-04 23:59:50+00:00,@Banterm42404691 @MrHarryCole Absolutely one s...,0,0,['COP26'],"{'_type': 'snscrape.modules.twitter.User', 'us...",aquitainexox
1,2021-11-04 23:59:48+00:00,"Please join us at a #COP26 side event ""Impleme...",2,1,['COP26'],"{'_type': 'snscrape.modules.twitter.User', 'us...",GEC_JCM_Info
2,2021-11-04 23:59:46+00:00,#India’s huge solar uptake has boosted #climat...,1,0,"['India', 'climate', 'COP26']","{'_type': 'snscrape.modules.twitter.User', 'us...",zpnine
3,2021-11-04 23:59:39+00:00,Reunión #COP26 Reunión mundial de países sobre...,0,0,"['COP26', 'AcuerdoDeParis', 'LenguajeClaro']","{'_type': 'snscrape.modules.twitter.User', 'us...",AsoPalabrasCl
4,2021-11-04 23:59:35+00:00,@_pln_id PLN terdepan dukung pemanfaatan EBT🍃\...,0,0,"['COP26', 'PLNGreen']","{'_type': 'snscrape.modules.twitter.User', 'us...",Crstianst
...,...,...,...,...,...,...,...
7611,2021-11-04 13:20:36+00:00,"ClimateChange is no more only a challenge, it’...",5,0,"['Climate', 'ClimateAction', 'COP26', 'climate...","{'_type': 'snscrape.modules.twitter.User', 'us...",AqsaYounasRana
7612,2021-11-04 13:20:18+00:00,We confronted the coal baron this morning! Fuc...,3,0,"['JoeManchin', 'JoeManchinSenatorForSale', 'Jo...","{'_type': 'snscrape.modules.twitter.User', 'us...",pete4peace
7613,2021-11-04 13:19:58+00:00,Feeling simply disgusted by countries such as ...,0,0,"['china', 'usa', 'india', 'COP26Glasgow', 'Fos...","{'_type': 'snscrape.modules.twitter.User', 'us...",mmill_landscape
7614,2021-11-04 13:19:45+00:00,🚨 Join us in calling for @Google and #Facebook...,0,0,"['Facebook', 'climatechange', 'disinformation'...","{'_type': 'snscrape.modules.twitter.User', 'us...",KarynCaplan
7615,2021-11-04 13:19:25+00:00,"There is no doubt! ""The science is clear: to k...",0,0,"['COP26Glasgow', 'COP26', 'ClimateActionNow', ...","{'_type': 'snscrape.modules.twitter.User', 'us...",DrDuly

In [47]:
del df_tw['column_2']

In [48]:
df_tw

,date,content,likeCount,quoteCount,hashtags,twitter_id
0,2021-11-04 23:59:50+00:00,@Banterm42404691 @MrHarryCole Absolutely one s...,0,0,['COP26'],aquitainexox
1,2021-11-04 23:59:48+00:00,"Please join us at a #COP26 side event ""Impleme...",2,1,['COP26'],GEC_JCM_Info
2,2021-11-04 23:59:46+00:00,#India’s huge solar uptake has boosted #climat...,1,0,"['India', 'climate', 'COP26']",zpnine
3,2021-11-04 23:59:39+00:00,Reunión #COP26 Reunión mundial de países sobre...,0,0,"['COP26', 'AcuerdoDeParis', 'LenguajeClaro']",AsoPalabrasCl
4,2021-11-04 23:59:35+00:00,@_pln_id PLN terdepan dukung pemanfaatan EBT🍃\...,0,0,"['COP26', 'PLNGreen']",Crstianst
...,...,...,...,...,...,...
7611,2021-11-04 13:20:36+00:00,"ClimateChange is no more only a challenge, it’...",5,0,"['Climate', 'ClimateAction', 'COP26', 'climate...",AqsaYounasRana
7612,2021-11-04 13:20:18+00:00,We confronted the coal baron this morning! Fuc...,3,0,"['JoeManchin', 'JoeManchinSenatorForSale', 'Jo...",pete4peace
7613,2021-11-04 13:19:58+00:00,Feeling simply disgusted by countries such as ...,0,0,"['china', 'usa', 'india', 'COP26Glasgow', 'Fos...",mmill_landscape
7614,2021-11-04 13:19:45+00:00,🚨 Join us in calling for @Google and #Facebook...,0,0,"['Facebook', 'climatechange', 'disinformation'...",KarynCaplan
7615,2021-11-04 13:19:25+00:00,"There is no doubt! ""The science is clear: to k...",0,0,"['COP26Glasgow', 'COP26', 'ClimateActionNow', ...",DrDuly

In [49]:
df_tw.to_csv ('organized_dataframe.csv', index = None, header=True)

## Extra: 
rest of the code will be in the cleaning notebook

In [50]:
df_tw['twitter_id'].unique()

array(['aquitainexox', 'GEC_JCM_Info', 'zpnine', ..., 'AqsaYounasRana',
       'mmill_landscape', 'DrDuly'], dtype=object)

In [51]:
df_tw.groupby('twitter_id').first()

,date,content,likeCount,quoteCount,hashtags
twitter_id,,,,,
0xLelouch,2021-11-04 22:17:11+00:00,@kasta_app About to add on my ports fav @IOEN_...,0,0,"['COP26', 'IOEN', 'Blockchain']"
102ethology,2021-11-04 18:50:30+00:00,The burning of fossil fuels has helped humans ...,0,0,"['FossilFuels', 'ClimateCrisis', 'behaviour']"
11pistache,2021-11-04 23:00:58+00:00,#COP26 #COP26Glasgow #ClimateAction #climate #...,0,0,"['COP26', 'COP26Glasgow', 'ClimateAction', 'cl..."
12345dubalier,2021-11-04 22:49:12+00:00,"Gonzalo Cardona Molina, el Señor de los Loros;...",2,0,['COP26']
13sealite,2021-11-04 23:23:34+00:00,@MartySilkHack It’s a good thing covid is gett...,0,0,['COP26']
...,...,...,...,...,...
zopeful_hq,2021-11-04 15:41:02+00:00,Whatever the policies and pledges that come fr...,2,0,"['COP26', 'ClimateCrisis', 'ClimateAction', 'c..."
zoranhorus,2021-11-03 07:35:29+00:00,They come to me in #GlasgowCop26 acting to ta...,0,0,['GlasgowCop26']
zpnine,2021-11-04 23:59:46+00:00,#India’s huge solar uptake has boosted #climat...,1,0,"['India', 'climate', 'COP26']"
zurichcanada,2021-11-04 19:20:31+00:00,#Climatechange is a consequence of our actions...,1,0,['Climatechange']
zuz64,2021-11-02 19:43:04+00:00,#cop26 I don't want to be political so let's j...,1,0,"['cop26', 'COP26Glasgow', 'ClimateAction', 'cl..."

In [52]:
df_tw['hastags'] = df1_clean_col['hashtags']

In [53]:
df_tw

,date,content,likeCount,quoteCount,hashtags,twitter_id,hastags
0,2021-11-04 23:59:50+00:00,@Banterm42404691 @MrHarryCole Absolutely one s...,0,0,['COP26'],aquitainexox,['COP26']
1,2021-11-04 23:59:48+00:00,"Please join us at a #COP26 side event ""Impleme...",2,1,['COP26'],GEC_JCM_Info,['COP26']
2,2021-11-04 23:59:46+00:00,#India’s huge solar uptake has boosted #climat...,1,0,"['India', 'climate', 'COP26']",zpnine,"['India', 'climate', 'COP26']"
3,2021-11-04 23:59:39+00:00,Reunión #COP26 Reunión mundial de países sobre...,0,0,"['COP26', 'AcuerdoDeParis', 'LenguajeClaro']",AsoPalabrasCl,"['COP26', 'AcuerdoDeParis', 'LenguajeClaro']"
4,2021-11-04 23:59:35+00:00,@_pln_id PLN terdepan dukung pemanfaatan EBT🍃\...,0,0,"['COP26', 'PLNGreen']",Crstianst,"['COP26', 'PLNGreen']"
...,...,...,...,...,...,...,...
7611,2021-11-04 13:20:36+00:00,"ClimateChange is no more only a challenge, it’...",5,0,"['Climate', 'ClimateAction', 'COP26', 'climate...",AqsaYounasRana,"['WorldBank', 'ClimateCrisis']"
7612,2021-11-04 13:20:18+00:00,We confronted the coal baron this morning! Fuc...,3,0,"['JoeManchin', 'JoeManchinSenatorForSale', 'Jo...",pete4peace,['ClimateCrisis']
7613,2021-11-04 13:19:58+00:00,Feeling simply disgusted by countries such as ...,0,0,"['china', 'usa', 'india', 'COP26Glasgow', 'Fos...",mmill_landscape,"['COP26', 'Offsets', 'Carbon', 'ClimateCrisis'..."
7614,2021-11-04 13:19:45+00:00,🚨 Join us in calling for @Google and #Facebook...,0,0,"['Facebook', 'climatechange', 'disinformation'...",KarynCaplan,NaN
7615,2021-11-04 13:19:25+00:00,"There is no doubt! ""The science is clear: to k...",0,0,"['COP26Glasgow', 'COP26', 'ClimateActionNow', ...",DrDuly,"['COP26', 'COP26Glasgow', 'Glasgow', 'ClimateA..."

In [54]:
#for i in df1_clean_col['user']:
#df1_clean_col['user']['username']

In [55]:
#user_unique =df1_clean_col['user'].value_counts()

In [56]:
#len(user_unique)

In [57]:
#df1_user_groupby = df1_clean_col.groupby('user').first()

In [58]:
#len(df1_user_groupby['user'])

In [59]:
#list(df1_user_groupby['content'])

## Cleaning round #1

In [60]:
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer, ENGLISH_STOP_WORDS
from sklearn.decomposition import NMF, TruncatedSVD, LatentDirichletAllocation

#### Common data cleaning steps on all text:

-Make text all lower case

-Remove punctuation

-Remove numerical values

-Remove common non-sensical text (/n)

-Tokenize text

-Remove stop words

In [61]:
'''Make text lowercase, remove text in square brackets, remove punctuation and remove words containing numbers.'''
import re
import string

def clean_text_round1(text):
    
    text = text.lower()
    text = re.sub('\[.*?\]', '', text)
    text = re.sub('[%s]' % re.escape(string.punctuation), '', text)
    text = re.sub('\w*\d\w*', '', text)
    return text

In [62]:
# Apply a second round of cleaning
def clean_text_round2(text):
    '''Get rid of some additional punctuation and non-sensical text that was missed the first time around.'''
    text = re.sub('[‘’“”…]', '', text)
    text = re.sub('\n', '', text)
    return text

In [63]:
clean_txt_rd1 = []
for i in range(len(df_tw['content'])):
    clean_txt_rd1.append(clean_text_round1(df_tw['content'][i]))

In [64]:
df_tw['clean_rd1'] = clean_txt_rd1

In [65]:
clean_txt_rd2 = []
for i in range(len(df_tw['content'])):
    clean_txt_rd2.append(clean_text_round2(df_tw['clean_rd1'][i]))

In [66]:
df_tw['content'][0]

'@Banterm42404691 @MrHarryCole Absolutely one self indulgent ego trip!! #COP26'

In [67]:
clean_txt_rd1[0]

' mrharrycole absolutely one self indulgent ego trip '

In [68]:
clean_txt_rd2[0]

' mrharrycole absolutely one self indulgent ego trip '

In [69]:
df_tw['clean_rd2'] = clean_txt_rd2

In [70]:
df_tw

,date,content,likeCount,quoteCount,hashtags,twitter_id,hastags,clean_rd1,clean_rd2
0,2021-11-04 23:59:50+00:00,@Banterm42404691 @MrHarryCole Absolutely one s...,0,0,['COP26'],aquitainexox,['COP26'],mrharrycole absolutely one self indulgent ego...,mrharrycole absolutely one self indulgent ego...
1,2021-11-04 23:59:48+00:00,"Please join us at a #COP26 side event ""Impleme...",2,1,['COP26'],GEC_JCM_Info,['COP26'],please join us at a side event implementing t...,please join us at a side event implementing t...
2,2021-11-04 23:59:46+00:00,#India’s huge solar uptake has boosted #climat...,1,0,"['India', 'climate', 'COP26']",zpnine,"['India', 'climate', 'COP26']",india’s huge solar uptake has boosted climate ...,indias huge solar uptake has boosted climate g...
3,2021-11-04 23:59:39+00:00,Reunión #COP26 Reunión mundial de países sobre...,0,0,"['COP26', 'AcuerdoDeParis', 'LenguajeClaro']",AsoPalabrasCl,"['COP26', 'AcuerdoDeParis', 'LenguajeClaro']",reunión reunión mundial de países sobre cambi...,reunión reunión mundial de países sobre cambi...
4,2021-11-04 23:59:35+00:00,@_pln_id PLN terdepan dukung pemanfaatan EBT🍃\...,0,0,"['COP26', 'PLNGreen']",Crstianst,"['COP26', 'PLNGreen']",plnid pln terdepan dukung pemanfaatan ebt🍃\n \...,plnid pln terdepan dukung pemanfaatan ebt🍃 pln...
...,...,...,...,...,...,...,...,...,...
7611,2021-11-04 13:20:36+00:00,"ClimateChange is no more only a challenge, it’...",5,0,"['Climate', 'ClimateAction', 'COP26', 'climate...",AqsaYounasRana,"['WorldBank', 'ClimateCrisis']",climatechange is no more only a challenge it’s...,climatechange is no more only a challenge its ...
7612,2021-11-04 13:20:18+00:00,We confronted the coal baron this morning! Fuc...,3,0,"['JoeManchin', 'JoeManchinSenatorForSale', 'Jo...",pete4peace,['ClimateCrisis'],we confronted the coal baron this morning fuck...,we confronted the coal baron this morning fuck...
7613,2021-11-04 13:19:58+00:00,Feeling simply disgusted by countries such as ...,0,0,"['china', 'usa', 'india', 'COP26Glasgow', 'Fos...",mmill_landscape,"['COP26', 'Offsets', 'Carbon', 'ClimateCrisis'...",feeling simply disgusted by countries such as ...,feeling simply disgusted by countries such as ...
7614,2021-11-04 13:19:45+00:00,🚨 Join us in calling for @Google and #Facebook...,0,0,"['Facebook', 'climatechange', 'disinformation'...",KarynCaplan,NaN,🚨 join us in calling for google and facebook m...,🚨 join us in calling for google and facebook m...
7615,2021-11-04 13:19:25+00:00,"There is no doubt! ""The science is clear: to k...",0,0,"['COP26Glasgow', 'COP26', 'ClimateActionNow', ...",DrDuly,"['COP26', 'COP26Glasgow', 'Glasgow', 'ClimateA...",there is no doubt the science is clear to keep...,there is no doubt the science is clear to keep...

In [71]:
stop_words = ENGLISH_STOP_WORDS.union(['math'])

In [72]:
corpus = df_tw['clean_rd2'].fillna(value='')

In [73]:
tfidf = TfidfVectorizer(stop_words=stop_words)

tweet_word_matrix = tfidf.fit_transform(corpus)

vocab = tfidf.get_feature_names()

# NMF

In [74]:
nmf = NMF(n_components=5)

nmf.fit(tweet_word_matrix)

/Users/amirreza/opt/anaconda3/lib/python3.8/site-packages/sklearn/decomposition/_nmf.py:312: FutureWarning: The 'init' value, when 'init=None' and n_components is less than n_samples and n_features, will be changed from 'nndsvd' to 'nndsvda' in 1.1 (renaming of 0.26).
  warnings.warn(("The 'init' value, when 'init=None' and "

NMF(n_components=5)

### Tweet-Topic Matrix

In [75]:
tweet_topic_matrix = nmf.transform(tweet_word_matrix)

In [76]:
tweet_topic_matrix

array([[2.06058043e-04, 0.00000000e+00, 1.00960787e-03, 1.58474323e-03,
        0.00000000e+00],
       [1.01094509e-02, 3.12663625e-05, 1.25331375e-03, 9.96163551e-04,
        1.66847862e-03],
       [3.15491181e-02, 0.00000000e+00, 2.89010957e-03, 1.56094554e-04,
        0.00000000e+00],
       ...,
       [1.33949728e-02, 1.01905501e-03, 4.30908644e-02, 8.34875370e-04,
        0.00000000e+00],
       [3.82044490e-02, 0.00000000e+00, 7.96328088e-02, 0.00000000e+00,
        0.00000000e+00],
       [6.13999466e-02, 0.00000000e+00, 4.49802912e-02, 0.00000000e+00,
        0.00000000e+00]])

In [77]:
tweet_topic_matrix_df = pd.DataFrame(tweet_topic_matrix).add_prefix('topic_')

In [78]:
tweet_topic_matrix_df

       topic_0   topic_1   topic_2   topic_3   topic_4
0     0.000206  0.000000  0.001010  0.001585  0.000000
1     0.010109  0.000031  0.001253  0.000996  0.001668
2     0.031549  0.000000  0.002890  0.000156  0.000000
3     0.000000  0.023773  0.000000  0.000000  0.000000
4     0.000321  0.000000  0.000000  0.000807  0.000298
...        ...       ...       ...       ...       ...
7611  0.063671  0.000574  0.056698  0.000000  0.000000
7612  0.000000  0.000000  0.040915  0.000232  0.000112
7613  0.013395  0.001019  0.043091  0.000835  0.000000
7614  0.038204  0.000000  0.079633  0.000000  0.000000
7615  0.061400  0.000000  0.044980  0.000000  0.000000

[7616 rows x 5 columns]

In [79]:
tweet_topic_matrix_df[['raw_tweets', 'clean_tweets']] = df_tw[['content', 'clean_rd2']]
tweet_topic_matrix_df.head()

,topic_0,topic_1,topic_2,topic_3,topic_4,raw_tweets,clean_tweets
0,0.000206,0.000000,0.001010,0.001585,0.000000,@Banterm42404691 @MrHarryCole Absolutely one s...,mrharrycole absolutely one self indulgent ego...
1,0.010109,0.000031,0.001253,0.000996,0.001668,"Please join us at a #COP26 side event ""Impleme...",please join us at a side event implementing t...
2,0.031549,0.000000,0.002890,0.000156,0.000000,#India’s huge solar uptake has boosted #climat...,indias huge solar uptake has boosted climate g...
3,0.000000,0.023773,0.000000,0.000000,0.000000,Reunión #COP26 Reunión mundial de países sobre...,reunión reunión mundial de países sobre cambi...
4,0.000321,0.000000,0.000000,0.000807,0.000298,@_pln_id PLN terdepan dukung pemanfaatan EBT🍃\...,plnid pln terdepan dukung pemanfaatan ebt🍃 pln...

In [80]:
word_topic_matrix_df = pd.DataFrame(nmf.components_, columns=vocab).T.add_prefix('topic_')
word_topic_matrix_df

             topic_0   topic_1   topic_2   topic_3  topic_4
aafccanada  0.000249  0.000000  0.000000  0.000000      0.0
aafcholos   0.000249  0.000000  0.000000  0.000000      0.0
aahuk       0.000000  0.000000  0.003767  0.000000      0.0
aan         0.000495  0.004094  0.000000  0.002664      0.0
aaneen      0.000059  0.000374  0.000000  0.000006      0.0
...              ...       ...       ...       ...      ...
𝙁𝘼𝙎𝙃𝙄𝙊𝙉     0.000000  0.000000  0.000000  0.002045      0.0
𝙂𝙊𝙀𝙎        0.000000  0.000000  0.000000  0.002045      0.0
𝙄𝙉          0.000000  0.000000  0.000000  0.002045      0.0
𝙏𝙊          0.000000  0.000000  0.000000  0.002045      0.0
𝙓𝙍          0.000000  0.000000  0.000000  0.002045      0.0

[32669 rows x 5 columns]

## Topic Interpretation

In [81]:
for tweet in tweet_topic_matrix_df.sort_values(by='topic_0', ascending=False).head(10)['raw_tweets'].values:
    print(tweet)
    print()

#climatechange https://t.co/DGRQoA3oIR

#ClimateChange #UN https://t.co/1y4TvQ6Epd

#climatechange https://t.co/VW2eaLfZ7r

#climatechange #cop26 https://t.co/BM06dFoeWB

It never was about #climatechange https://t.co/JySjzW4duj

#ClimateChange https://t.co/8dXn7HUT4z

https://t.co/gK5V0rTAQc #ClimateChange 🌎

https://t.co/WHP0ygVjUy - Climate Action Plan 2021 - #climatechange  https://t.co/RlstfyBGF9

Why our #CLIMATE targets keep changing, and how that helps fight climate change even if we miss them https://t.co/XorUcaGck2  #GlobalWarming #climatechange

Why our #CLIMATE targets keep changing, and how that helps fight climate change even if we miss them https://t.co/JeIHclZ4HI #GPWX #GlobalWarming #climatechange

In [82]:
word_topic_matrix_df.sort_values(by='topic_0', ascending=False).head(10)

                topic_0   topic_1   topic_2   topic_3   topic_4
climatechange  1.579665  0.000000  0.000000  0.000000  0.000000
climate        1.436625  0.000000  0.210954  0.000000  0.000000
change         0.791316  0.000000  0.000000  0.000000  0.292070
amp            0.586349  0.005124  0.028858  0.022372  0.000000
action         0.359644  0.000000  0.011259  0.023271  0.000000
world          0.336710  0.000000  0.041022  0.026055  0.445667
global         0.336689  0.021286  0.016754  0.029595  0.021051
globalwarming  0.270350  0.000000  0.063351  0.000000  0.000000
people         0.259119  0.000000  0.058925  0.000000  0.027591
energy         0.254126  0.002262  0.009738  0.020621  0.000000

In [83]:
def top_tweets(tweet_topic_matrix_df, topic, n_tweets):
    return (tweet_topic_matrix_df
            .sort_values(by=topic, ascending=False)
            .head(n_tweets)['raw_tweets']
            .values)

def top_words(word_topic_matrix_df, topic, n_words):
    return (word_topic_matrix_df
            .sort_values(by=topic, ascending=False)
            .head(n_words))[topic]

In [88]:
for tweet in top_tweets(tweet_topic_matrix_df, 'topic_1', 5):
    print(tweet)
    print()

Con la Declaración de Glasgow el turismo asume la responsabilidad sobre la acción climática en la actividad y que el cambio climático y la contaminación ponen en peligro el desarrollo turístico. La sostenibilidad es esencial en el turismo que viene!
#COP26 https://t.co/eQ8ZZI5SjV

El @GobiernoMX no firmó el acuerdo global para detener y revertir la pérdida de bosques y la degradación de la tierra para el 2030, como lo hicieron más de 100 líderes mundiales en la #GlasgowCop26. https://t.co/SezfZle1hk

El @GobiernoMX
 no firmó el acuerdo global para detener y revertir la pérdida de bosques y la degradación de la tierra para el 2030, como lo hicieron más de 100 líderes mundiales en la #GlasgowCop26.
https://t.co/tLEspW6ECN

López aseguró que la firma del convenio para revertir la deforestación en la #GlasgowCop26 fue una idea de su gobierno inspirada en el programa 'Sembrando Vida'.

Pero el presidente es tan humilde que ni asistió a la cumbre para que le dieran las gracias.

Pobre Tartufo

#Internacional La cumbre del clima en #GlasgowCop26 Sin la #China el principal contaminador del planeta, la cumbre es una pérdida de tiempo, El títere de
@BarackObama @JoeBiden aprovechó la oportunidad para dormir, En Serio! Este es el Presidente de los #EstadosUnidos No Jodas🙄 https://t.co/QHvHX6CsWr

In [85]:
top_words(word_topic_matrix_df, 'topic_1', 10)

la      1.506986
en      1.084278
el      0.957200
que     0.632336
los     0.467427
del     0.433201
para    0.424016
se      0.346824
por     0.342325
es      0.307929
Name: topic_1, dtype: float64

In [86]:
for tweet in top_tweets(tweet_topic_matrix_df, 'topic_3', 10):
    print(tweet)
    print()

#GlasgowCop26 #Glasgow https://t.co/vsrcj8TgoG

[@giotoon ]
#COP26 #Glasgow #GlasgowCop26 https://t.co/OANpZjY5V1

#COP26Glasgow #CoP26 #Glasgow #GlasgowCop26 https://t.co/v7a6ypTSix

#Glasgow #GlasgowCop26 https://t.co/2vCOt04opR

#COP26Glasgow #CoP26 #Glasgow #GlasgowCop26 https://t.co/EGHWiv3jnK

#GlasgowCop26
#Glasgow https://t.co/IkMP9LhG0T

@COP26  #COP26  #Glasgow  #GlasgowCop26  👂🧐👂
👇👇👇👇

https://t.co/dqGm2SNjJg

#GlasgowCop26 #glasgow https://t.co/PrMZ0x01GO

#GlasgowCop26 #Glasgow #COP26 https://t.co/w1zW1crGVs

#GlasgowCop26 #Glasgow_CO2nference #Glasgow #ClimateEmergency
https://t.co/4f0L8W8Txe https://t.co/aO7HFZ66aZ

In [87]:
top_words(word_topic_matrix_df, 'topic_3', 10)

glasgow           2.081667
dailyprosperes    0.179062
ofrecido          0.173402
contenido         0.173402
encamina          0.173402
economía          0.170334
hacia             0.167840
futuro            0.163916
verde             0.160165
scotland          0.139211
Name: topic_3, dtype: float64